changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - octocat
  categories:
    - title: Breaking changes
      labels:
        - breaking-change
    - title: New features
      labels:
        - enhancement
    - title: Bug fixes
      labels:
        - bug
    - title: Style fixes
      labels:
        - style
    - title: CI
      labels:
        - ci
    - title: Build
      labels:
        - build
    - title: Refactoring
      labels:
        - refactoring
    - title: Test
      labels:
        - test
    - title: Example
      labels:
        - example
    - title: Documentation
      labels:
        - documentation
    - title: Other changes
      labels:
        - "*"
