[workspace]
members = [
  "geojson-source",
  "on-load",
  "popup",
  "set-data",
  "simple",
  "sycamore-simple",
  "add-image",
  "leptos-simple",
  "custom-icons-with-markers",
  "draggable-marker",
  "change-map-style",
  "get-features-under-the-mouse-pointer",
]
