name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: ["*"]

env:
  MAPBOX_TOKEN: token
  CARGO_TERM_COLOR: always

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Run build and tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Rust toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        components: rustfmt, clippy
    - name: Build crate and examples
      run: |
        cargo build --workspace --all-targets --all-features
        pushd examples; cargo build --workspace --all-targets --all-features; popd
    - name: Clippy
      run: |
        cargo clippy --workspace --all-targets --all-features -- --deny clippy::all
        pushd examples; cargo clippy --workspace --all-targets --all-features -- --deny clippy::all; popd
    - name: Install nextest
      uses: taiki-e/install-action@nextest
    - name: Unit tests
      run: cargo nextest run --retries 3 --no-tests=pass
