name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: ["*"]
jobs:
  build:
    name: Run build on ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Build
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --workspace --all-targets --all-features
      env:
        MAPBOX_TOKEN: token
    - name: Clippy
      uses: actions-rs/cargo@v1
      with:
        command: clippy
        args: --workspace --all-targets --all-features -- --deny clippy::all
    - name: Install nextest
      uses: taiki-e/install-action@nextest
    - name: Tests
      uses: actions-rs/cargo@v1
      with:
        command: nextest
        args: run --all
