name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: ["*"]

env:
  MAPBOX_TOKEN: token

jobs:
  test:
    name: Run build and tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --workspace --all-targets --all-features
    - name: Clippy
      uses: actions-rs/cargo@v1
      with:
        command: clippy
        args: --workspace --all-targets --all-features -- --deny clippy::all
    - name: Install nextest
      uses: taiki-e/install-action@nextest
    - name: Tests
      uses: actions-rs/cargo@v1
      with:
        command: nextest
        args: run --all
